CREATE TABLE IF NOT EXISTS jobs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    parent_job_id INTEGER,
    step_id INTEGER,
    held INTEGER NOT NULL DEFAULT 0,
    priority INTEGER NOT NULL DEFAULT 0,
    name TEXT NOT NULL,
    user_name TEXT NOT NULL DEFAULT 'unknown',
    state TEXT NOT NULL,
    partition TEXT NOT NULL DEFAULT 'gpu',
    command TEXT NOT NULL,
    cwd TEXT NOT NULL,
    requested_cpus INTEGER NOT NULL,
    requested_tasks INTEGER NOT NULL DEFAULT 1,
    requested_memory_mb INTEGER NOT NULL,
    requested_gpus INTEGER NOT NULL DEFAULT 0,
    allocation_only INTEGER NOT NULL DEFAULT 0,
    dependency TEXT,
    array_job_id INTEGER,
    array_task_id INTEGER,
    array_task_count INTEGER,
    array_task_limit INTEGER,
    max_rss_kb INTEGER,
    submit_time INTEGER NOT NULL,
    start_time INTEGER,
    end_time INTEGER,
    pid INTEGER,
    pgid INTEGER,
    exit_code INTEGER,
    state_reason TEXT NOT NULL DEFAULT '',
    term_signal INTEGER,
    time_limit_secs INTEGER,
    assigned_gpus TEXT NOT NULL DEFAULT '',
    script_path TEXT NOT NULL DEFAULT '',
    stdout_path TEXT NOT NULL DEFAULT '',
    stderr_path TEXT NOT NULL DEFAULT '',
    export_env TEXT NOT NULL DEFAULT '',
    open_mode TEXT NOT NULL DEFAULT 'truncate',
    warning_signal INTEGER,
    warning_signal_seconds INTEGER
);
