CREATE TABLE IF NOT EXISTS jobs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    user_name TEXT NOT NULL DEFAULT 'unknown',
    state TEXT NOT NULL,
    partition TEXT NOT NULL DEFAULT 'gpu',
    command TEXT NOT NULL,
    cwd TEXT NOT NULL,
    requested_cpus INTEGER NOT NULL,
    requested_memory_mb INTEGER NOT NULL,
    requested_gpus INTEGER NOT NULL DEFAULT 0,
    submit_time INTEGER NOT NULL,
    start_time INTEGER,
    end_time INTEGER,
    pid INTEGER,
    pgid INTEGER,
    exit_code INTEGER,
    state_reason TEXT NOT NULL DEFAULT '',
    term_signal INTEGER,
    time_limit_secs INTEGER,
    assigned_gpus TEXT NOT NULL DEFAULT '',
    script_path TEXT NOT NULL DEFAULT '',
    stdout_path TEXT NOT NULL DEFAULT '',
    stderr_path TEXT NOT NULL DEFAULT ''
);
